#!/bin/sh
##############################################################################
## Gradle start up script for POSIX generated by Gradle
##############################################################################
APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
# Add default JVM options here
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'
# Use the maximum available, or set MAX_FD != -1 to use that value
MAX_FD="maximum"
warn () { echo "$*"; }
die () { echo; echo "$*"; echo; exit 1; }
# Determine the Java command to use to start the JVM
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi
# Increase the maximum file descriptors if we can
MAX_FD_LIMIT=`ulimit -H -n`
if [ $? -eq 0 ] ; then
    ulimit -n $MAX_FD_LIMIT
fi
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
